// Generated by NuttyMod Studios.
using System;

Console.WriteLine("{\"name\":\"ortainHORROR\",\"version\":\"1.0\",\"author\":\"nuttyinc578\",\"description\":\"Created in NuttyMod Studios with a 7-sided studio shape.\",\"shapes\":[{\"name\":\"ortainHORROR Gem\",\"kind\":\"polygon\",\"sides\":7,\"size\":33,\"color\":[255,142,105],\"weight\":1.0}],\"events\":[{\"name\":\"ortainHORROR Pulse\",\"duration\":6,\"wind\":420,\"gravity_scale\":0.55,\"spawn_count\":4,\"banner\":\"ortainHORROR Pulse is active!\",\"color\":[255,142,105]}]}");
