# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ["the_cube_beta_summer.py"],
    pathex=["addons"],
    binaries=[],
    datas=[
        ("icon.ico", "."),
        ("normal_icon.ico", "."),
        ("halloween_cube_icon.png", "."),
        ("error_update_logo.png", "."),
        ("LICENCE.txt", "."),
        ("click.mp3", "."),
        ("fall_music.mp3", "."),
        ("THIRD_PARTY_NOTICES.txt", "."),
        ("addons", "addons"),
        ("themes", "themes"),
        ("repair_payload", "repair_payload"),
        ("cpe-backend.json", "."),
        ("cpeloader.py", "."),
        ("cpeloader_core_runtime.js", "."),
        ("cpeloader_core.rb", "."),
    ],
    hiddenimports=["cpe_rephysics.engine", "cpe_rephysics.physics", "cpe_rephysics.particles", "cpe_rephysics.protocol"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="The Cube Beta Halloween Update",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=["icon.ico"],
    version="summer_version.txt",
)
