package main
import("crypto/rand";"crypto/subtle";"encoding/hex";"encoding/json";"flag";"fmt";"io";"net";"os";"path/filepath";"regexp";"strings";"time")
type Account struct{Username string `json:"username"`;Token string `json:"token"`}
type Request struct{Secret string `json:"secret"`;Action string `json:"action"`;Username string `json:"username"`;Proof string `json:"proof"`;Token string `json:"token"`}
type Response struct{OK bool `json:"ok"`;Service string `json:"service,omitempty"`;Account bool `json:"account,omitempty"`;Username string `json:"username,omitempty"`;Error string `json:"error,omitempty"`}
var validName=regexp.MustCompile(`^[A-Za-z0-9_.-]{3,32}$`)
func readAccount(path string)(Account,error){var v Account;b,e:=os.ReadFile(path);if e!=nil{return v,e};e=json.Unmarshal(b,&v);return v,e}
func writeAccount(path string,v Account)error{if e:=os.MkdirAll(filepath.Dir(path),0700);e!=nil{return e};b,e:=json.MarshalIndent(v,"","  ");if e!=nil{return e};t:=path+".new";if e=os.WriteFile(t,append(b,'\n'),0600);e!=nil{return e};return os.Rename(t,path)}
func newToken()(string,error){b:=make([]byte,32);if _,e:=rand.Read(b);e!=nil{return "",e};return hex.EncodeToString(b),nil}
func send(c net.Conn,v Response){_ = json.NewEncoder(c).Encode(v)}
func handle(c net.Conn,secret,path string){defer c.Close();_ = c.SetDeadline(time.Now().Add(10*time.Second));var q Request;if json.NewDecoder(io.LimitReader(c,65536)).Decode(&q)!=nil{send(c,Response{Error:"invalid request"});return};if subtle.ConstantTimeCompare([]byte(q.Secret),[]byte(secret))!=1{send(c,Response{Error:"forbidden"});return};switch q.Action{case"health":_,e:=readAccount(path);send(c,Response{OK:true,Service:"nuttymod-go-auth",Account:e==nil});case"register":if !validName.MatchString(q.Username)||len(q.Proof)<4{send(c,Response{Error:"Use a 3-32 character account name and an auth phrase of at least 4 characters."});return};t,e:=newToken();if e!=nil||writeAccount(path,Account{q.Username,t})!=nil{send(c,Response{Error:"account could not be saved"});return};send(c,Response{OK:true,Username:q.Username});case"login":a,e:=readAccount(path);ok:=e==nil&&subtle.ConstantTimeCompare([]byte(strings.TrimSpace(q.Token)),[]byte(a.Token))==1;if !ok{send(c,Response{Error:"login failed"});return};send(c,Response{OK:true,Username:a.Username});default:send(c,Response{Error:"unknown action"})}}
func main(){port:=flag.Int("port",0,"local TCP port");path:=flag.String("account","","local account file");flag.Parse();secret:=os.Getenv("NUTTYMOD_AUTH_SECRET");if secret==""||*path==""{fmt.Fprintln(os.Stderr,"missing auth configuration");os.Exit(2)};listener,e:=net.Listen("tcp",fmt.Sprintf("127.0.0.1:%d",*port));if e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(3)};actual:=listener.Addr().(*net.TCPAddr).Port;ready,_:=json.Marshal(map[string]any{"ready":true,"service":"go-auth","port":actual});fmt.Println(string(ready));for{c,e:=listener.Accept();if e!=nil{os.Exit(4)};go handle(c,secret,*path)}}
